version: '3'

services:
  myserver:
    
    image: docker.io/shihaji/myeurekaserver
    ports:
    - 8761
    
  myjpa:
    image: docker.io/shihaji/myeurekajpa
    environment:
    - eureka.client.service-url.defaultZone=http://myserver:8761/eureka/
    - eureka.instance.prefer-ip-address=true
    - spring.datasource.url=jdbc:mysql://mydatabase.crmstchzv6s3.ap-south-1.rds.amazonaws.com:3306/mydatabase
    - spring.datasource.username=root
    - spring.datasource.password=rootroot
    ports:
    - 8085
    depends_on:
    - myserver
    
  myclient:
    image: docker.io/shihaji/myeurekaclient
    environment:
    - eureka.client.service-url.defaultZone=http://myserver:8761/eureka/
    - eureka.instance.prefer-ip-address=true
    ports:
    - 8086
    depends_on:
    - myserver
    - myjpa
  
  myauth:
    image: docker.io/shihaji/myauth
    environment:
    - eureka.client.service-url.defaultZone=http://myserver:8761/eureka/
    - eureka.instance.prefer-ip-address=true
    - spring.datasource.url=jdbc:mysql://mydatabase.crmstchzv6s3.ap-south-1.rds.amazonaws.com:3306/mydatabase
    - spring.datasource.username=root
    - spring.datasource.password=rootroot
    
    ports:
    - 8090
    depends_on:
    - myserver
  
  mygateway:
    image: docker.io/shihaji/mygateway
    environment:
    - eureka.client.service-url.defaultZone=http://myserver:8761/eureka/
    - eureka.instance.prefer-ip-address=true
    - spring.cloud.gateway.routes[0].id=MYEUREKACLIENT
    - spring.cloud.gateway.routes[0].uri=lb://MYEUREKACLIENT
    - spring.cloud.gateway.routes[0].predicates[0]=Path=/getEmp/**
    
    - spring.cloud.gateway.routes[1].id=MYAUTH
    - spring.cloud.gateway.routes[1].uri=lb://MYAUTH
    - spring.cloud.gateway.routes[1].predicates[0]=Path=/authenticate/**
    - spring.cloud.gateway.routes[1].predicates[1]=Path=/validate/**
    
    
    ports:
    - 8087
    depends_on:
    - myserver
    - myauth
    - myclient
               
        
    
      
  